[validator.dotslash]
include_files = ["bin/*"]

[validator.biome]
include_files = [
  "**/*.css",
  "**/*.htm",
  "**/*.html",
  "**/*.js",
  "**/*.json",
  "**/*.jsonc",
  "**/*.jsx",
  "**/*.ts",
  "**/*.tsx",
]
exclude_files = ["bin/*"]

[validator.gitleaks]
include_files = ["**"]

[validator.ini]
include_files = ["**/*.cfg", "**/*.ini"]

[validator.python-black]
include_files = ["**/*.py"]

[validator.python-filename]
include_files = ["**/*.py"]

[validator.python-shadow-import]
include_files = ["**/*.py"]

[validator.pyupgrade]
include_files = ["**/*.py"]

[validator.rustfmt]
include_files = ["**/*.rs"]

[validator.shellcheck]
include_files = [
  "**/*.bash",
  "**/*.sh",
  "bin/aws-create-hosted-zone",
  "bin/aws-write-secret",
  "bin/bootstrap",
  "bin/cdk",
  "bin/pre-commit",
  "bin/test",
  "bin/validate",
]

[validator.shfmt]
include_files = [
  "**/*.bash",
  "**/*.sh",
  "bin/aws-create-hosted-zone",
  "bin/aws-write-secret",
  "bin/bootstrap",
  "bin/cdk",
  "bin/pre-commit",
  "bin/test",
  "bin/validate",
]

[validator.taplo]
include_files = ["**/*.toml"]

[validator.terraform-fmt]
include_files = ["**/*.tf", "**/*.tfvars"]

[validator.xml]
include_files = ["**/*.xml"]

[validator.yamlfmt]
include_files = ["**/*.yaml", "**/*.yml"]

[validator.yamllint]
include_files = ["**/*.yaml", "**/*.yml"]

[validator.case-conflict]
include_files = ["**"]

[validator.conflict-markers]
include_files = ["**"]

[validator.keep-sorted]
include_files = ["**"]

[validator.filename-chars]
include_files = ["**"]

[validator.executable-extension]
include_files = ["**"]

[validator.file-size]
include_files = ["**"]

[validator.symlink]
include_files = ["**"]

[validator.tabs]
include_files = ["**"]
exclude_files = ["**/Makefile", "**/*.make"]

[validator.unicode]
include_files = ["**"]
exclude_files = ["**/*.md"]

[validator.trailing-newline]
include_files = ["**"]

[validator.trailing-whitespace]
include_files = ["**"]
exclude_files = ["**/*.md"]
