[validator.python-black]
include_files = ["**/*.py"]

[validator.python-filename]
include_files = ["**/*.py"]

[validator.python-shadow-import]
include_files = ["**/*.py"]

[validator.case-conflict]
include_files = ["**"]

[validator.conflict-markers]
include_files = ["**"]

[validator.keep-sorted]
include_files = ["**"]

[validator.filename-chars]
include_files = ["**"]

[validator.executable-extension]
include_files = ["**"]

[validator.file-size]
include_files = ["**"]

[validator.symlink]
include_files = ["**"]

[validator.tabs]
include_files = ["**"]
exclude_files = ["**/Makefile", "**/*.make"]

[validator.unicode]
include_files = ["**"]
exclude_files = ["**/*.md"]

[validator.trailing-newline]
include_files = ["**"]

[validator.trailing-whitespace]
include_files = ["**"]
exclude_files = ["**/*.md"]
