[foundation]
public_domain = "chiiiirs.com"
private_domain = "chiiiirs.net"

[webfinger]
subject = "acct:chris@chiiiirs.com"
oidc_issuer_application = "tailscale"

[authentik]
subdomain = "auth"
image_version = "2026.2"

[data]
master_secret_name = "data/database"

[data.instance]
instance_type = "t4g.small"
allocated_storage_gib = 20

[authentik.db]
name = "authentik"
secret_name = "authentik/database"

[authentik.server]
cpu = 1024
memory_limit_mib = 2048
desired_count = 1
min_healthy_percent = 100

[authentik.worker]
cpu = 1024
memory_limit_mib = 2048
desired_count = 1
min_healthy_percent = 100

[authentik.smtp]
host = "smtp.chiiiirs.com"
from_email_address = "authentik@chiiiirs.com"

[headscale]
headscale_subdomain = "headscale"
headplane_subdomain = "headplane"
dns_subdomain = "ts"
headscale_image_version = "0.26.1"
headplane_image_version = "0.6.1"
oidc_issuer_application = "headscale"
dns_nameservers = ["1.1.1.1", "9.9.9.9"]
log_level = "info"

[headscale.db]
name = "headscale"
secret_name = "headscale/database"

[headscale.headscale]
cpu = 512
memory_limit_mib = 1024
desired_count = 1
min_healthy_percent = 100

[headscale.headplane]
cpu = 256
memory_limit_mib = 512
desired_count = 1
min_healthy_percent = 100
