"""coturn (TURN) + livekit-server (Element-Call SFU) on a single EC2.

Co-located by design (per the matrix-voice-video doc): one
Elastic IP, one multi-SAN TLS cert covering both subdomains,
shared service lifecycle. The host runs in its own dedicated VPC
(single-tier public, no NAT) -- the only traffic to and from this
box is internet-facing media + signaling, so foundation's
multi-tier VPC buys us nothing here.

Three secrets are auto-generated by CDK at first deploy and
consumed by both this stack (via the instance role) and
downstream stacks (Synapse for the TURN shared secret;
LkJwtStack for the LiveKit key pair):

  matrix/turn-shared-secret    coturn <-> Synapse HMAC key
  livekit/api-key              LiveKit JWT identifier
  livekit/api-secret           LiveKit JWT signing key
"""

from dataclasses import dataclass
from typing import cast

from aws_cdk import (
    Aws,
    CfnOutput,
    Stack,
    aws_ec2 as ec2,
    aws_iam as iam,
    aws_route53 as route53,
    aws_route53_targets as route53_targets,
    aws_s3_assets as s3_assets,
    aws_secretsmanager as secretsmanager,
)
from constructs import Construct

from ..models.asset_loader import AssetLoader
from ..models.foundation_exports import FoundationExports
from ..models.turn_config import TurnConfig
from ..models.turn_exports import TurnExports

# Pinned upstream version of livekit-server (Element-Call SFU).
# Release artifact name pattern:
#   livekit_<version>_linux_amd64.tar.gz under tag v<version>.
# Bump when Element-Call drops a hard requirement on a newer
# LiveKit; otherwise stability > novelty.
LIVEKIT_VERSION = "1.11.0"

# Names of the auto-generated secrets shared with downstream
# stacks. Kept stable so we can rotate the underlying value
# without re-plumbing imports.
TURN_SHARED_SECRET_NAME = "matrix/turn-shared-secret"
LIVEKIT_API_KEY_SECRET_NAME = "livekit/api-key"
LIVEKIT_API_SECRET_SECRET_NAME = "livekit/api-secret"


def parse_bool(s: str) -> bool:
    return s.strip().lower() == "true"


@dataclass(frozen=True)
class TurnImports:
    cfg: TurnConfig
    foundation: FoundationExports
    assets: AssetLoader


class TurnStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        imports: TurnImports,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        cfg = imports.cfg
        foundation = imports.foundation
        user_data_replace = parse_bool(
            self.node.try_get_context("userDataReplace") or "false"
        )

        turn_fqdn = f"{cfg.turn_subdomain}.{foundation.public_domain}"
        livekit_fqdn = f"{cfg.livekit_subdomain}.{foundation.public_domain}"

        ###
        # VPC: single-tier public, no NAT. The instance only talks
        # to the internet (clients) and AWS APIs (SSM, Secrets
        # Manager, Route53); foundation's private-egress tier
        # would just add NAT-gateway cost for no benefit.
        vpc = ec2.Vpc(
            self,
            "Vpc",
            max_azs=2,
            nat_gateways=0,
            subnet_configuration=[
                ec2.SubnetConfiguration(
                    name="public",
                    subnet_type=ec2.SubnetType.PUBLIC,
                    cidr_mask=24,
                ),
            ],
        )

        ###
        # Auto-generated shared secrets. CDK generates a random
        # `{"secret":"..."}` payload at first deploy; subsequent
        # deploys reuse it. Rotating means deleting the secret
        # and redeploying both this stack and its consumers.
        def _random_secret(
            construct_id: str, secret_name: str
        ) -> secretsmanager.Secret:
            return secretsmanager.Secret(
                self,
                construct_id,
                secret_name=secret_name,
                generate_secret_string=secretsmanager.SecretStringGenerator(
                    secret_string_template="{}",
                    generate_string_key="secret",
                    password_length=64,
                    exclude_punctuation=True,
                ),
            )

        turn_shared_secret = _random_secret("TurnSharedSecret", TURN_SHARED_SECRET_NAME)
        livekit_api_key_secret = _random_secret(
            "LiveKitApiKey", LIVEKIT_API_KEY_SECRET_NAME
        )
        livekit_api_secret_secret = _random_secret(
            "LiveKitApiSecret", LIVEKIT_API_SECRET_SECRET_NAME
        )

        ###
        # Instance role: SSM for management, Route53 for certbot
        # DNS-01, Secrets Manager for the three shared secrets.
        role = iam.Role(
            self,
            "InstanceRole",
            assumed_by=iam.ServicePrincipal(
                "ec2.amazonaws.com"
            ),  # pyright: ignore[reportArgumentType]
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "AmazonSSMManagedInstanceCore"
                ),
            ],
        )
        for s in (
            turn_shared_secret,
            livekit_api_key_secret,
            livekit_api_secret_secret,
        ):
            s.grant_read(role)
        # certbot-dns-route53 wants list-zones + get-change account-
        # wide, but the actual record write is scoped to our zone.
        role.add_to_principal_policy(
            iam.PolicyStatement(
                actions=["route53:ListHostedZones", "route53:GetChange"],
                resources=["*"],
            )
        )
        role.add_to_principal_policy(
            iam.PolicyStatement(
                actions=["route53:ChangeResourceRecordSets"],
                resources=[
                    f"arn:aws:route53:::hostedzone/{foundation.public_zone.hosted_zone_id}",
                ],
            )
        )

        ###
        # Security group: all six service-port families to
        # 0.0.0.0/0.
        sg = ec2.SecurityGroup(
            self,
            "InstanceSecurityGroup",
            vpc=vpc,
            allow_all_outbound=True,
            description="coturn + livekit-server",
        )
        # coturn signaling/relay.
        sg.add_ingress_rule(
            ec2.Peer.any_ipv4(), ec2.Port.udp(3478), "coturn STUN/TURN UDP"
        )
        sg.add_ingress_rule(
            ec2.Peer.any_ipv4(), ec2.Port.tcp(3478), "coturn STUN/TURN TCP"
        )
        sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(5349), "coturn TURN-TLS")
        sg.add_ingress_rule(
            ec2.Peer.any_ipv4(),
            ec2.Port.udp_range(cfg.relay_min_port, cfg.relay_max_port),
            "coturn relay UDP range",
        )
        # LiveKit signaling (nginx terminates TLS on 443 and
        # forwards to 127.0.0.1:7880; the 7880 port stays
        # internal). RTC media goes direct.
        sg.add_ingress_rule(
            ec2.Peer.any_ipv4(), ec2.Port.tcp(443), "livekit signaling via nginx"
        )
        sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(7881), "livekit RTC TCP")
        sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.udp(7882), "livekit RTC UDP")

        ###
        # Asset bundle (config templates the host renders at boot).
        asset = s3_assets.Asset(
            self,
            "ConfigAsset",
            path=str(imports.assets.turn_assets_path()),
        )
        asset.grant_read(role)

        ###
        # Render user-data. Python substitutes @@KEY@@ here for
        # CDK-side constants; turnserver.conf.tmpl and
        # livekit.yaml.tmpl use __KEY__ for the host-side render
        # step (different markers so the two layers don't
        # collide).
        user_data_template = imports.assets.read_text("turn", "user-data.sh.tmpl")
        substitutions = {
            "AWS_REGION": Aws.REGION,
            "ASSET_S3_URI": f"s3://{asset.s3_bucket_name}/{asset.s3_object_key}",
            "LIVEKIT_VERSION": LIVEKIT_VERSION,
            "TURN_SHARED_SECRET_NAME": TURN_SHARED_SECRET_NAME,
            "LIVEKIT_API_KEY_SECRET_NAME": LIVEKIT_API_KEY_SECRET_NAME,
            "LIVEKIT_API_SECRET_SECRET_NAME": LIVEKIT_API_SECRET_SECRET_NAME,
            "PUBLIC_DOMAIN": foundation.public_domain,
            "TURN_FQDN": turn_fqdn,
            "LIVEKIT_FQDN": livekit_fqdn,
            "RELAY_MIN_PORT": str(cfg.relay_min_port),
            "RELAY_MAX_PORT": str(cfg.relay_max_port),
        }
        rendered = user_data_template
        for key, value in substitutions.items():
            rendered = rendered.replace(f"@@{key}@@", value)
        user_data = ec2.UserData.custom(rendered)

        ubuntu_ami = ec2.MachineImage.from_ssm_parameter(
            "/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id",
            os=ec2.OperatingSystemType.LINUX,
        )

        instance = ec2.Instance(
            self,
            "TurnInstance",
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PUBLIC),
            security_group=sg,
            role=role,  # pyright: ignore[reportArgumentType]
            instance_type=ec2.InstanceType(cfg.instance_type),
            machine_image=ubuntu_ami,
            user_data=user_data,
            user_data_causes_replacement=user_data_replace,
            require_imdsv2=True,
            block_devices=[
                ec2.BlockDevice(
                    device_name="/dev/sda1",
                    volume=ec2.BlockDeviceVolume.ebs(
                        volume_size=10,
                        encrypted=True,
                        volume_type=ec2.EbsDeviceVolumeType.GP3,
                        delete_on_termination=True,
                    ),
                ),
            ],
        )

        ###
        # Elastic IP -- stable address that survives instance
        # replacement. Route53 A records for both subdomains
        # point here.
        eip = ec2.CfnEIP(self, "Eip", domain="vpc")
        ec2.CfnEIPAssociation(
            self,
            "EipAssociation",
            allocation_id=eip.attr_allocation_id,
            instance_id=instance.instance_id,
        )

        for record_id, record_name in (
            ("TurnARecord", cfg.turn_subdomain),
            ("LivekitARecord", cfg.livekit_subdomain),
        ):
            route53.ARecord(
                self,
                record_id,
                zone=foundation.public_zone,
                record_name=record_name,
                target=route53.RecordTarget.from_ip_addresses(eip.attr_public_ip),
            )

        ###
        # Pre-render the `turn_uris:` list Synapse expects. Three
        # protocol forms: plain UDP (preferred), plain TCP
        # (NAT-traversal fallback), TLS-TCP (corporate-firewall
        # fallback on a port-443-ish path).
        turn_uris = [
            f"turn:{turn_fqdn}?transport=udp",
            f"turn:{turn_fqdn}?transport=tcp",
            f"turns:{turn_fqdn}?transport=tcp",
        ]

        self.exports = TurnExports(
            turn_fqdn=turn_fqdn,
            livekit_fqdn=livekit_fqdn,
            turn_shared_secret=cast(secretsmanager.ISecret, turn_shared_secret),
            livekit_url=f"wss://{livekit_fqdn}",
            livekit_api_key_secret=cast(secretsmanager.ISecret, livekit_api_key_secret),
            livekit_api_secret_secret=cast(
                secretsmanager.ISecret, livekit_api_secret_secret
            ),
            turn_uris=turn_uris,
        )

        CfnOutput(self, "InstanceId", value=instance.instance_id)
        CfnOutput(self, "ElasticIp", value=eip.attr_public_ip)
        CfnOutput(
            self,
            "SsmSessionExample",
            value=f"aws ssm start-session --target {instance.instance_id}",
        )
